import { promises as fs } from 'fs';
import path from 'path';
import crypto from 'crypto';

type Options = {
  tag?: string | null;
  quiet?: boolean;
};

const root = path.resolve(import.meta.dir, '..');
const targetPath = path.join(root, 'src', 'build-info.ts');

function formatTimestamp(d: Date): string {
  return d.toISOString();
}

function makeId(tag?: string | null): string {
  const now = new Date();
  const iso = now.toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
  const random = crypto.randomBytes(3).toString('hex');
  const prefix = tag && tag.trim().length ? `${tag.trim()}-` : '';
  return `${prefix}${iso}-${random}`;
}

export async function generateBuildInfo(options: Options = {}) {
  const tag = options.tag ?? process.env.BUILD_TAG ?? null;
  const provided = process.env.BUILD_ID;
  const timestamp = formatTimestamp(new Date());
  const id = provided && provided.trim().length ? provided.trim() : makeId(tag);

  const contents = `// Generated by scripts/build-info.ts\nexport const BUILD_ID = '${id}';\nexport const BUILD_TIMESTAMP = '${timestamp}';\n`;

  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.writeFile(targetPath, contents, 'utf8');

  if (!options.quiet) {
    console.log(`Generated build info: ${id} (${timestamp})`);
  }

  return { id, timestamp, tag: tag ?? undefined, file: targetPath };
}

if (import.meta.main) {
  generateBuildInfo().catch((err) => {
    console.error('build-info generation failed:', err);
    process.exit(1);
  });
}

